<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>linkerhand_gazebo_control</name>
  <version>1.0.0</version>
  <description>把 Linker Hand 手势关节目标稳定同步到 Gazebo Sim 并反馈仿真状态。</description>

  <maintainer email="2303886347@qq.com">2303886347</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>linkerhand_l30_left_description</exec_depend>
  <exec_depend>linkerhand_l30_right_description</exec_depend>
  <exec_depend>linkerhand_gazebo_plugin</exec_depend>
  <exec_depend>linkerhand_model_profiles</exec_depend>
  <exec_depend>linkerhand_retargeting</exec_depend>
  <exec_depend>mediapipe_hand_pose</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>usb_camera_demo</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
