<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>linkerhand_gazebo_plugin</name>
  <version>0.1.0</version>
  <description>Linker Hand 在线多关节位置控制的 Gazebo System 插件。</description>

  <maintainer email="2303886347@qq.com">2303886347</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ignition-gazebo6</depend>
  <depend>ignition-msgs8</depend>
  <depend>ignition-plugin1</depend>
  <depend>ignition-transport11</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
