<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>linkerhand_retargeting</name>
  <version>1.0.0</version>
  <description>将 MediaPipe 人手角度标定、滤波并重定向为 Linker Hand 左右手关节目标。</description>

  <maintainer email="2303886347@qq.com">2303886347</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>hand_pose_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>linkerhand_l30_left_description</exec_depend>
  <exec_depend>linkerhand_l30_right_description</exec_depend>
  <exec_depend>linkerhand_model_profiles</exec_depend>
  <exec_depend>mediapipe_hand_pose</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>tf2_ros</exec_depend>
  <exec_depend>usb_camera_demo</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
